# Μόνιμος χώρος για τα δεδομένα των services.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-data
  namespace: library-cloud
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
  namespace: library-cloud
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: library-cloud
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: library-cloud
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
